export const DEFAULT_QUERY_PARAMS = {
  limit: 27,
  offset: 0,
};

export const TYPES_COLORS = {
  fairy: "#E397D1",
  normal: "#aab09f",
  flying: "#7DA6DE",
  poison: "#B468B7",
  ground: "#78513",
  rock: "#78513c",
  bug: "#94BC4A",
  ghost: "#846ab6",
  ice: "#70cbd4",
  colorless: "#c7bff7",
  lightning: "#f6f739",
  electric: "#f6f739",
  metal: "#877f7f",
  darkness: "#4f575f",
  // "Marine": ,
  // "Sand": ,
  // "Temporal": ,
  // "Lunar": ,
  // "Solar": ,
  // "Wood": ,
  // "Mud": ,
  // "Insect": ,
  // "Bug": ,
  // "Snow": ,
  // "Magma" ,
  // "Wind": ,
  // "Cosmic": ,
};
